statuses:
  holiday:
    emoji: ':palm_tree:'
    presence: away
    short_name: ooo
    status_text: On holiday
  lunch:
    emoji: ':burrito:'
    presence: away
    short_name: lunch
    status_text: Out to lunch
  at_work:
    emoji:
    presence: auto
    short_name: work
    status_text: ''
  wfh:
    emoji: ':house_with_garden:'
    presence: auto
    short_name: wfh
    status_text: Working from home

workspace_credentials:
  work:
    token: xoxp-1234
    short_name: work
  office:
    token: xoxp-1234
    short_name: personal
