statuses:
  holiday:
    emoji: ':palm_tree:'
    presence: away
    short_name: ooo
    status_text: On holiday
  lunch:
    emoji: ':burrito:'
    presence: away
    short_name: lunch
    status_text: Out to lunch
  at_work:
    emoji: ':male-technologist::skin-tone-3:'
    presence: auto
    short_name: work
    status_text: Hard at work
  wfh:
    emoji: ':house_with_garden:'
    presence: auto
    short_name: wfh
    status_text: Working from home

all_statuses:
  - holiday
  - lunch
  - at_work
  - wfh

workspace_credentials:
  work:
    token: xoxp-123
    short_name: wk
  office:
    token: xoxp-123
    short_name: of
